I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 585, in script
    if Resutl >=8:
  File "game/script.rpy", line 585, in <module>
    if Resutl >=8:
NameError: name 'Resutl' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 585, in script
    if Resutl >=8:
  File "E:\новела\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "E:\новела\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\новела\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 585, in <module>
    if Resutl >=8:
NameError: name 'Resutl' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Путь Программиста 1.0
Tue Oct 17 17:54:29 2023
